### ISSUE TITLE
Custom location for snippets

### ISSUE THREAD

**Issue by andreasnymark** [pedroborges/kirby-xml-sitemap#1]
Would it be possible to set a custom location for the snippets? 

I’m using routes for my blog posts, adding year to the url. The blog posts are not separated into folders for each year, but I want this visible in the url. E.g. `example.com/blog/2017/post-title`. 

This is currently solved via a custom snippets/page.php:

	<?php if ( $page->intendedTemplate() === 'post' ) : ?>
	<loc><?= html( $page->parent()->url() . '/' . $page->date( 'Y') . '/' . $page->slug() ) ?></loc>
	<?php else : ?>
	<loc><?= html( $page->url() ) ?></loc>
	<?php endif ?>

**Comment by pedroborges** [comment]
You could use the `sitemap.process` option to modify the `url()` of blog posts alone, but there's a better way to achieve what you want by using [page models](https://getkirby.com/docs/developer-guide/advanced/models).

```php
<?php // site/models/post.php

class Postpage extends Page
{
    public function url()
    {
        return $this->parent()->url() . '/' . $this->date( 'Y') . '/' . $this->slug();
    }
}
```

That way you will get the correct URL for blog posts anywhere in your templates and XML Sitemap too. Just use `$page->url()` as you would without routing.

**Comment by andreasnymark** [comment]
That will help me in so many cases. Thanks!
