### ISSUE TITLE
includeInvisibles for parent object

### ISSUE THREAD

**Issue by bnomei** [pedroborges/kirby-xml-sitemap#4]
a setting to not add a page if parent is invisible even if page is visible would be nice.

**Comment by pedroborges** [comment]
You can manipulate the pages collection anyway you want by using the `sitemap.process` option:

```php
c::set('sitemap.process', function($pages) {
    return $pages->filter(function($page) {
        // Remove children of invisible pages
        if ($page->parent()->isInvisible()) {
            return false;
        }

        // Keep all other pages
        return true;
    });
});
```

The plugin would never be able to cover all use cases, this option is powerful enough to let you include/exclude any page to/from the sitemap on any website.
