### ISSUE TITLE
Not include not translated pages

### ISSUE THREAD

**Issue by thinkbigger** [pedroborges/kirby-xml-sitemap#7]
Hi,
the plugin should not include untranslated pages. It assumes that there is a page for all the site languages, which could not be the case.

Is there a filter that I can apply?

Thanks

**Comment by pedroborges** [comment]
That's currently possible. You can use the `sitemap.process` option to modify the pages collection before it's passed to the sitemap template.

```php
c::set('sitemap.process', function($pages) {
    return $pages->filter(function($page) {
        // Remove non-translated pages
        if (! $page->text()->isTranslated()) {
            return false;
        }

        // Keep all other pages
        return true;
    });
});
```
