### ISSUE TITLE
Option to load custom snippet

### ISSUE THREAD

**Issue by LeBenLeBen** [pedroborges/kirby-xml-sitemap#9]
To have more control on the final output, it would be great to have an option to use a custom snippet.

My own use case would be to alter the "canonical" loop and limit the pages to those that are actually translated in the other languages.

**Comment by pedroborges** [comment]
Hi @LeBenLeBen, you can actually do that already. XML Sitemap uses a snippet registered as `sitemap.page` to generate each individual page listing on the final `sitemap.xml`.

You can override it by copying the `site/plugins/xml-sitemap/snippets/page.php` file to `site/snippets/sitemap.page.php` and changing it to fit your needs. In your case you'll need to change this section on the snippet:

```php
<?php if ($languages && $languages->count() > 1) : ?>
    <?php foreach ($languages as $lang) : ?>
    <xhtml:link hreflang="<?= $lang->code() ?>" href="<?= html($page->url($lang->code())) ?>" rel="alternate" />
    <?php endforeach ?>
<?php endif ?>
```

`$languages` in that context is the same as `site()->languages()`.

That's is a Kirby feature that I wasn't aware of, snippets inside `site/snippets` take precedence over the ones registered with the Kirby register. I'll add a note about this on the `readme`.

**Comment by LeBenLeBen** [comment]
@pedroborges Indeed, awesome, thank you for the tip!
